### ISSUE TITLE
Cannot install 1.1 version

### ISSUE THREAD

**Issue by Truenya** [cosmolabs-ru/sswidget_android#2]
Устройство  Xiaomi readmi note 8 Pro
Фирмаварь MUI 12.0.8
Андроид 10QP1A 190711.020

![Screenshot_2021-08-08-13-40-59-373_com google android packageinstaller](https://user-images.githubusercontent.com/51529891/128629252-1a35fe30-8981-4464-81a9-188a4fe89db9.jpg)
![Screenshot_2021-08-08-13-40-56-281_com android vending](https://user-images.githubusercontent.com/51529891/128629253-22257f92-ca20-4f07-9583-ac7ecd1970dc.jpg)

Возникают неотображаемые ошибки при установке.
На версии 1.0 все работает.

**Comment by cosmolabs-ru** [comment]
Гугол думает, что его защиты умнее вас. На санкционном хуавее без гугла проблемы нет. Проблема не на моей стороне. Софтварь предлагается как есть, без гарантий работоспособности. Это было просто актом поддержки идеи sssecond и упражнением в программировании. Fork & contribute.
-- 
Google thinks its Play is smarter than you. Release installs fine on a Google-less Huawei (yet it has other problems though). Software is provided as is, so it all is not my problem, feel free to fork & contribute.

**Comment by Truenya** [comment]
> 
> ## Гугол думает, что его защиты умнее вас. На санкционном хуавее без гугла проблемы нет. Проблема не на моей стороне. Софтварь предлагается как есть, без гарантий работоспособности. Это было просто актом поддержки идеи sssecond и упражнением в программировании. Fork & contribute.
> 
> Google thinks its Play is smarter than you. Release installs fine on a Google-less Huawei (yet it has other problems though). Software is provided as is, so it all is not my problem, feel free to fork & contribute.

Защита и на 1.0 ругается, защита вообще на все на свете ругается, это не ответ.
Там кнопка есть плюнуть на защиту и энивей поставить.
